Added checks for elevation and domain admin privs
TrimarcJake/Locksmith pull request #17
Opened 2023-02-14 14:08 UTC by SamErde

Created functions to check for elevation (run as admin) and to check for domain admin privs. The DA privs check can be modified for specific AD group roles as needed. I will be performing further testing and potentially tweak the DA check to look up SID instead of group name. Future commits can make use of these functions.

2023-02-14 14:10 UTC, TrimarcJake commented
Oooh. Unexpected PRs are fun! I'll take a look at this tonight or tomorrow so we can discuss Thursday.

2023-02-14 14:17 UTC, SamErde commented
OK! This doesn’t change functionality at all yet. It just adds two functions that can be put to use for closing to-dos and enhancements.

2023-02-16 17:09 UTC, TrimarcJake requested changes

2023-02-16 17:09 UTC, TrimarcJake commented on Invoke-Locksmith.ps1
> +function Test-IsDomainAdmin {
Let's rename this function to Test-IsADAdmin

2023-02-16 17:09 UTC, TrimarcJake commented on Invoke-Locksmith.ps1
> +    if (-not (
Let's re-write this function to remove the -not  from the check.

2023-02-16 17:09 UTC, TrimarcJake commented on Invoke-Locksmith.ps1
> +    if (-not (
To clarify:
We should check if the user **is** a member of those groups instead of checking if the user is not a member of the groups.

2023-02-17 18:08 UTC, SamErde commented
Added the `Test-IsLocalAccountSession` function which is a step towards avoiding issue #9.

2023-02-26 19:59 UTC, TrimarcJake approved these changes
Looks great! Merging!

2023-02-26 19:59 UTC, merged